name: Docker Build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
      - 'start.sh'
      - 'docker-compose.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          push: true
          tags: ghcr.io/restoremonarchyplugins/rpi5-unturned-server:latest
